//! The wire reading of CP437: identity below `0x80`, one table above it.

use mud_core::cp437::{HIGH, decode_wire, encode};

#[test]
fn bytes_below_0x80_are_themselves() {
    for b in 0u8..0x80 {
        assert_eq!(decode_wire(&[b]), String::from(b as char), "byte {b:#04x}");
    }
}

#[test]
fn control_bytes_pass_through() {
    // The ANSI escapes, the line endings and the anti-bot backspaces all
    // live below 0x20 and must survive decoding.
    assert_eq!(decode_wire(b"\x1b[1m\r\n\x08"), "\x1b[1m\r\n\x08");
}

#[test]
fn the_high_half_is_box_drawing_and_accents() {
    assert_eq!(decode_wire(&[0xc9, 0xcd, 0xbb]), "\u{2554}\u{2550}\u{2557}");
    assert_eq!(decode_wire(&[0x82]), "\u{e9}");
}

#[test]
fn every_byte_survives_a_round_trip() {
    let all: Vec<u8> = (0u8..=0xff).collect();
    assert_eq!(encode(&decode_wire(&all)), all);
}

#[test]
fn unmappable_characters_become_question_marks() {
    assert_eq!(encode("\u{4e2d}"), b"?".to_vec());
}

#[test]
fn encode_can_synthesize_the_telnet_iac_byte() {
    // CP437 0xFF is a non-breaking space, and 0xFF is also telnet IAC. A
    // caller on a telnet path must double it. Pinned here so the hazard lives
    // with the function instead of in one caller's comment.
    assert_eq!(encode("\u{a0}"), vec![0xff]);
}

/// `cp437-reference.txt`: bytes `0x80..=0xFF` decoded by Python's stdlib
/// `cp437` codec, in byte order, followed by one newline. Generated by:
///
/// ```sh
/// python3 -c "import sys; sys.stdout.write(bytes(range(0x80,0x100)).decode('cp437') + '\n')"
/// ```
///
/// That codec is an authority independent of `HIGH`, so this fixture checks
/// the table's contents rather than just its shape.
const REFERENCE: &str = include_str!("cp437-reference.txt");

#[test]
fn the_table_matches_the_independent_reference() {
    let reference: Vec<char> = REFERENCE.trim_end_matches('\n').chars().collect();
    assert_eq!(reference.len(), 128, "cp437-reference.txt must hold exactly 128 characters");
    for (i, (&got, &want)) in HIGH.iter().zip(&reference).enumerate() {
        let b = i + 0x80;
        assert_eq!(got, want, "HIGH[{b:#04x}] is {got:?}, cp437-reference.txt says {want:?}");
    }
}
